version: '3.9'

services:
  postgre-cache:
    image: postgres:16.1-alpine
    #orignial: image: postgres:16.1
    container_name: postgre-cache
    env_file:
      - .env
    ports:
      - ${PG_PORT:?error}:${PG_PORT:?error}
    environment:
      - POSTGRES_USER=${PG_USER:?error}
      - POSTGRES_PASSWORD=${PG_PASSWORD:?error}
      - POSTGRES_DB=${PG_DB:?error}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${PG_USER} -d ${PG_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - codebasenetwork

  login-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: login-service
    env_file:
      - .env
    environment:
      - APP_PORT=${APP_SRV_PORT:?error}
      - APP_NAME=${APP_SRV_NAME:?error}
      - PG_URL=${APP_DB_PG_URL:?error}
      - KA_AUDIT=${TOPIC_AUDIT:?error}
      - KAFKA_BASE_ADD=${KAFKA_ADD:?error}
    ports:
      - ${APP_SRV_PORT:?error}
    depends_on:
      postgre-cache:
        condition: service_healthy
    restart: on-failure
    networks:
      - codebasenetwork

  # mailhog:
  #   image: cd2team/mailhog:1685232349
  #   # original: image: mailhog/mailhog:latest
  #   container_name: mailhog
  #   ports:
  #     - 1025:1025
  #     - 8025:8025
  #   restart: on-failure
  #   networks:
  #     - codebasenetwork

  nginx:
    # specifies the latest nginx image
    image: nginx:1.25.3-alpine
    # original: image: nginx:latest
    platform: linux/amd64
    container_name: nginx
    # Connects the conf file of the container to the conf file in our folder
    volumes:
      - ./devops/local/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    # It will start up the nginx only when all api containers have started
    depends_on:
      - login-service
    restart: on-failure
    # Connects the port 80 of the nginx container to localhost:80 or localhost
    ports:
      - ${NGINX_PORT:?error}:${NGINX_PORT:?error}
    networks:
      - codebasenetwork

networks:
  codebasenetwork:
    name: codebasenetwork
    external: true